{{- $name := include "buzzfeed-sso.name" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "buzzfeed-sso.fullname" . }}-proxy
  labels:
    app: {{ $name }}-proxy
    chart: {{ template "buzzfeed-sso.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - name: http
      port: {{ .Values.proxy.service.port }}
      targetPort: 4180
      protocol: TCP
  selector:
    app: {{ $name }}-proxy
    release: {{ .Release.Name }}
